-- ============================================================
-- Migration 002: Hotels Table
-- ============================================================
CREATE TABLE IF NOT EXISTS hotels (
  id              CHAR(36)        NOT NULL PRIMARY KEY,
  owner_id        CHAR(36)        NOT NULL,
  name            VARCHAR(200)    NOT NULL,
  slug            VARCHAR(250)    NOT NULL UNIQUE,
  description     TEXT            NULL,
  address         VARCHAR(255)    NOT NULL,
  city            VARCHAR(100)    NOT NULL,
  province        VARCHAR(100)    NOT NULL,
  country         VARCHAR(100)    NOT NULL DEFAULT 'Vietnam',
  latitude        DECIMAL(10,8)   NULL,
  longitude       DECIMAL(11,8)   NULL,
  star_rating     TINYINT         NULL,
  price_per_night DECIMAL(12,2)   NOT NULL,
  currency        VARCHAR(10)     NOT NULL DEFAULT 'VND',
  thumbnail       VARCHAR(255)    NULL,
  images          JSON            NULL,
  amenities       JSON            NULL,
  total_rooms     INT             NOT NULL DEFAULT 1,
  available_rooms INT             NOT NULL DEFAULT 1,
  check_in_time   VARCHAR(10)     NOT NULL DEFAULT '14:00',
  check_out_time  VARCHAR(10)     NOT NULL DEFAULT '12:00',
  is_active       TINYINT(1)      NOT NULL DEFAULT 1,
  is_verified     TINYINT(1)      NOT NULL DEFAULT 0,
  avg_rating      DECIMAL(3,2)    NOT NULL DEFAULT 0,
  total_reviews   INT             NOT NULL DEFAULT 0,
  created_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at      DATETIME        NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at      DATETIME        NULL,
  CONSTRAINT fk_hotel_owner FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE,
  INDEX idx_city     (city),
  INDEX idx_province (province),
  INDEX idx_price    (price_per_night),
  INDEX idx_rating   (avg_rating)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
