-- ============================================================
-- Migration 003: Tours Table
-- ============================================================
CREATE TABLE IF NOT EXISTS tours (
  id               CHAR(36)      NOT NULL PRIMARY KEY,
  created_by       CHAR(36)      NOT NULL,
  name             VARCHAR(200)  NOT NULL,
  slug             VARCHAR(250)  NOT NULL UNIQUE,
  description      TEXT          NULL,
  highlights       JSON          NULL,
  itinerary        JSON          NULL,
  includes         JSON          NULL,
  excludes         JSON          NULL,
  destination      VARCHAR(150)  NOT NULL,
  departure_city   VARCHAR(100)  NOT NULL,
  duration_days    INT           NOT NULL,
  duration_nights  INT           NOT NULL,
  max_group_size   INT           NOT NULL DEFAULT 20,
  min_group_size   INT           NOT NULL DEFAULT 1,
  price_per_person DECIMAL(12,2) NOT NULL,
  price_child      DECIMAL(12,2) NULL,
  currency         VARCHAR(10)   NOT NULL DEFAULT 'VND',
  category         ENUM('adventure','cultural','beach','city','nature','luxury','budget') NOT NULL DEFAULT 'cultural',
  difficulty       ENUM('easy','moderate','challenging') NOT NULL DEFAULT 'easy',
  thumbnail        VARCHAR(255)  NULL,
  images           JSON          NULL,
  is_active        TINYINT(1)    NOT NULL DEFAULT 1,
  is_featured      TINYINT(1)    NOT NULL DEFAULT 0,
  avg_rating       DECIMAL(3,2)  NOT NULL DEFAULT 0,
  total_reviews    INT           NOT NULL DEFAULT 0,
  total_bookings   INT           NOT NULL DEFAULT 0,
  created_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at       DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at       DATETIME      NULL,
  CONSTRAINT fk_tour_creator FOREIGN KEY (created_by) REFERENCES users(id),
  INDEX idx_destination (destination),
  INDEX idx_category    (category),
  INDEX idx_featured    (is_featured)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
